### ISSUE TITLE
对 UICollectionView 用 KVO 会不会有问题

### ISSUE THREAD

**Issue by howarduoz** [zekunyan/TTGTagCollectionView#1]
https://developer.apple.com/library/ios/documentation/General/Conceptual/DevPedia-CocoaCore/KVO.html
Although the classes of the UIKit framework generally do not support KVO, you can still implement it in the custom objects of your application, including custom views.

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/KeyValueObserving/Articles/KVOBasics.html
 Not all classes are KVO-compliant for all properties. You can ensure your own classes are KVO-compliant by following the steps described in KVO Compliance. Typically properties in Apple-supplied frameworks are only KVO-compliant if they are documented as such.

http://stackoverflow.com/questions/32511864/ios-9-kvo-no-longer-working
http://stackoverflow.com/questions/6612523/ios-how-do-i-know-if-a-property-is-kvo-compliant
http://stackoverflow.com/questions/6114261/how-reliable-is-kvo-with-uikit

**Comment by zekunyan** [comment]
@howarduoz 其实我一直都在担心这个问题=。=，目前来看好像没事
