### ISSUE TITLE
升级到最新2.0，Pod报 Generated duplicate UUIDs

### ISSUE THREAD

**Issue by rzshuo** [zekunyan/TTGTagCollectionView#105]
报如下警告，回退到1.11.2没有这个警告了。

Generated duplicate UUIDs

<img width="1182" alt="WX20210425-153934@2x" src="https://user-images.githubusercontent.com/57256049/115985021-763c8d00-a5dc-11eb-9ec2-a6c1f37c1f44.png">

**Comment by zekunyan** [comment]
我看下

**Comment by zekunyan** [comment]
@rzshuo 没有完整的错误信息？

**Comment by rzshuo** [comment]
@zekunyan 没有错误，就只有这一大大大大串警告⚠️，截屏显示的也就三分之一。
