### ISSUE TITLE
Access text(String) property of the tag in Swift

### ISSUE THREAD

**Issue by valenwalker** [zekunyan/TTGTagCollectionView#107]
i can not access the text property using swift. 

tag.content.text = Value of type 'TTGTextTagContent' has no member 'text'

**Comment by zekunyan** [comment]
`TTGTextTagContent` is just a abstract class. It has two subclass StringContent And AttributedStringContent. You should convert the `tag.content` to suitable class and access its value.

**Comment by onewhoz** [comment]
Converting will look like let tagtext : TTGTextTagStringContent = tag.content
        as! TTGTextTagStringContent
