### ISSUE TITLE
求解2个问题啊，非常感谢。

### ISSUE THREAD

**Issue by sharehoney** [zekunyan/TTGTagCollectionView#108]
1.是通过设置selectionLimit来实现【单选】吗？

2.当有【多个】TTGTextTagCollectionView的时候，我尝试通过下面的代理方法来改变【每个】TTGTextTagCollectionView的高度：
- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView updateContentSize:(CGSize)contentSize {}
--------- 可这样并不精确，请问有什么精确的办法吗？

---------------------------  非常感谢 ：）----------------------------------

【另外，QQ群怎么无法加入呢？】

**Comment by zekunyan** [comment]
1. 单选要自己通过delegate控制。
2. 用preferredMaxLayoutWidth + Autolayout自动设置高度

**Comment by sharehoney** [comment]
嗨，您好 ： 多谢回复，我试一下。

：）
