### ISSUE TITLE
标签中有4个字的汉字， 设置了tagTextFont属性，iPhone6p布局错乱

### ISSUE THREAD

**Issue by srn214** [zekunyan/TTGTagCollectionView#11]
标签中有4个字的汉字， 设置了tagTextFont属性，iPhone6p布局错乱
![snip20170215_4](https://cloud.githubusercontent.com/assets/14295747/22963861/6e8d1942-f390-11e6-981a-97a1d95b06b9.png)
![snip20170215_5](https://cloud.githubusercontent.com/assets/14295747/22963868/76e16418-f390-11e6-994a-f321a79d4845.png)

**Comment by zekunyan** [comment]
图看不到

**Comment by srn214** [comment]
图已上传，demo中修改的代码也已上传

**Comment by zekunyan** [comment]
你用的版本是啥？

**Comment by srn214** [comment]
最新版，刚从github中下载的

**Comment by zekunyan** [comment]
我的没有问题

![image](https://cloud.githubusercontent.com/assets/5687881/22966878/07d7b662-f39f-11e6-9deb-c1dfdebbc323.png)

![image](https://cloud.githubusercontent.com/assets/5687881/22966873/02fc21a0-f39f-11e6-8a4a-d53ca21f7b0d.png)

**Comment by srn214** [comment]
你在iPhone 7plus模拟器或者真机上运行就出有问题，iPhone7或者iPhone6上没有问题

**Comment by zekunyan** [comment]
看了下，是Demo的布局有问题，不影响库的使用
