### ISSUE TITLE
Error occur after using swift package manager to install TTGTagCollectionView

### ISSUE THREAD

**Issue by davidhsu1115** [zekunyan/TTGTagCollectionView#112]
After import TTGTags i got an error message. "Could not build Objective-C module 'TTGTags'"
Any idea how to resolve this issue?
<img width="1105" alt="截圖 2021-08-07 上午2 17 24" src="https://user-images.githubusercontent.com/10396887/128554710-b0e81172-ecc1-4e0b-b5fb-3547d06c2a96.png">

**Comment by zekunyan** [comment]
@davidhsu1115 Which version ?

**Comment by davidhsu1115** [comment]
I am using the latest version 2.0.1

**Comment by zekunyan** [comment]
@davidhsu1115 I try all day and still can't solve this problem... Maybe i need more time. You can try to use CocoaPods instead.

**Comment by davidhsu1115** [comment]
Sure take your time, I am temporary using CocoaPods now.

**Comment by zekunyan** [comment]
@davidhsu1115 You can try the new version 2.1.0.

**Comment by davidhsu1115** [comment]
Awesome! it works! Thanks a lot.

**Comment by zekunyan** [comment]
@davidhsu1115 Great !
