### ISSUE TITLE
How to add multiline support for a text in a tag.

### ISSUE THREAD

**Issue by rohita-personatech** [zekunyan/TTGTagCollectionView#114]
How to add multiline support for a text in a tag.

**Comment by zekunyan** [comment]
@rohita-personatech Set `maxWidth` in `TTGTextTagStyle`

**Comment by barkiiqbal** [comment]
@zekunyan It's not working for me, I set maxWidth and maxHeight to 0 still text is not expanding to multi lines.

**Comment by zekunyan** [comment]
@barkiiqbal Supporting multiline will mess up the current design. You can make you own "Text Tag View" based on `TTGTagCollectionView` from the bottom.

**Comment by iamsenzy** [comment]
@zekunyan Can you add numberOfLines to the style for the label?

**Comment by zekunyan** [comment]
The `numberOfLines` needs `maxWidth` at the same time. And it will be very strange when each text tag can has different height in each row...
