### ISSUE TITLE
How can i add a refresh control to it?

### ISSUE THREAD

**Issue by AnasAlmomany** [zekunyan/TTGTagCollectionView#12]
I was wondering if there is anyway to add a refresh control to it, I tried to check if I have any access to a scrollview, but unfortunately, I couldn't achieve this.

**Comment by zekunyan** [comment]
Now the inside scrollView will remove all the subViews in it when `reload`. So it will remove the refresh control view. The next version will export the inside scrollView and fix this problem. It's coming soon :)

**Comment by AnasAlmomany** [comment]
That would be very helpful , my main problem is that i need to put the tags inside a view controller and pull the controller down to refresh tags like refreshing a collection of multi-sized tag images , this approach is valid when using the text tags collection but here we go again i need to handle the events more effectively , thank you keep up the good work .

**Comment by zekunyan** [comment]
The new version 1.4.1 can support refresh control. I added a demo in the example project for using SVPullToRefresh with TTGTagCollectionView.
