### ISSUE TITLE
No such module 'TTGTagCollectionView'

### ISSUE THREAD

**Issue by iBlahji** [zekunyan/TTGTagCollectionView#120]
I'm using M1 Mac for my development while opening old code with the latest Xcode 13, I'm facing this issue.

I have tried to add Exclude architecture arm64 to my pods

**Comment by HLTangbinbin** [comment]
Im also facing this trouble with No such module 'TTGTags'

**Comment by zekunyan** [comment]
pod update try again ?

**Comment by denizdogan** [comment]
Did you try `import TTGTags` ?
