### ISSUE TITLE
请问：为啥指定的行数无效呢？

### ISSUE THREAD

**Issue by sharehoney** [zekunyan/TTGTagCollectionView#123]
如下，指定了2行：

        _whenTag.numberOfLines = 2;
        _whenTag.scrollDirection = TTGTagCollectionScrollDirectionHorizontal;

数据源中有3个标签字符串，但还是成一行显示，第三个标签就被遮住了一半。

—— 怎样断行呢？

多谢。

**Comment by zekunyan** [comment]
复现Demo代码麻烦提供下

**Comment by sharehoney** [comment]
多谢回复。

改成以下 就实现断行了：

 _whenTag.scrollDirection = TTGTagCollectionScrollDirectionVertical;
