### ISSUE TITLE
为什么最后一行宽度总是不对啊，怎么设置都无效

### ISSUE THREAD

**Issue by 542604974** [zekunyan/TTGTagCollectionView#124]
![191656466541_ pic](https://user-images.githubusercontent.com/15099430/176332267-e0149fa7-3fe7-4124-86c0-6a1eb5653941.jpg)

**Comment by 542604974** [comment]
alignment试了个遍， 
   _textTagCollectionView1.manualCalculateHeight = YES;
    _textTagCollectionView1.preferredMaxLayoutWidth = SCREEN_WIDTH - kIntervalDistance14 * 2;
都试了

**Comment by 542604974** [comment]
发现了是horizontalSpacing问题，我设置了就出现这种情况

**Comment by zekunyan** [comment]
请给出完整复现Demo
