### ISSUE TITLE
Horizontal two lines is not performing as expected

### ISSUE THREAD

**Issue by krutikazoodmall** [zekunyan/TTGTagCollectionView#131]
even though I have added numberOfLines and countPerSection parameters, it is not displaying multiple lines for horizontal mode.

`tagView.scrollDirection = .horizontal
        tagView.numberOfLines = 2
        tagView.selectionLimit = 10`

I need two lines .. each having maximum 10 tags

<img width="360" alt="Screenshot 2022-09-13 at 11 28 35 AM" src="https://user-images.githubusercontent.com/113358612/189821244-cab27c51-863b-43d0-8f6e-46a703b7aaaf.png">

**Comment by zekunyan** [comment]
Can you provide the whole Demo code ?

**Comment by krutikazoodmall** [comment]
[ViewController.swift.zip](https://github.com/zekunyan/TTGTagCollectionView/files/9554313/ViewController.swift.zip)

**Comment by zekunyan** [comment]
I don't have this problem.

![image](https://user-images.githubusercontent.com/5687881/189895695-9fee2c70-cbaa-41d4-87e0-b2a6a1333849.png)

**Comment by krutikazoodmall** [comment]
this is vertical. I need horizontal.

**Comment by zekunyan** [comment]
The new version 2.2.0 fix this problem.
