### ISSUE TITLE
On horizontal scroll direction collectionView gets uncontrolable width

### ISSUE THREAD

**Issue by Karahan00** [zekunyan/TTGTagCollectionView#132]
The tag collectionView gets a confusing width after scroll direction is set on horizontal.

`tagSelectorCollection.scrollDirection = TTGTagCollectionScrollDirection.horizontal`

See image what happens:
![Bug](https://user-images.githubusercontent.com/58490905/190000489-8f278a09-cccd-4de5-9c9b-ca8e7ff9d55f.png)

if I'am removeing the scrollDirection property than everything works fine. Can anyone help me?
![OK](https://user-images.githubusercontent.com/58490905/190000497-afda7d86-eed1-447d-95a1-4459ffed0cde.png)

**Comment by zekunyan** [comment]
The new version 2.2.0 fix this problem.

**Comment by Karahan00** [comment]
> The new version 2.2.0 fix this problem.

Thank you very much 💪🏽

**Comment by Karahan00** [comment]
> The new version 2.2.0 fix this problem.

Hey @zekunyan,

unfortunately now I'am faceing with a new problem. If I'am setting the `.direction` property the problem with the uncontrolable witdh is sloved but there is only one line inside the collectionView. If I'am setting the `.numberOfLines` property to `0` to get unlimited lines this didn't work. On vertical direction everything works fine.

![code](https://user-images.githubusercontent.com/58490905/190925969-517427e9-4477-4316-a4ab-c2f908a7b19f.png)

![bug](https://user-images.githubusercontent.com/58490905/190925964-9f8402b2-0ead-4765-b16d-a7745536e362.png)

Can you help me?

Greetings

**Comment by zekunyan** [comment]
Can you provide Demo code for this problem ?

**Comment by Karahan00** [comment]
> Can you provide Demo code for this problem ?

Unfortunely I can't share an fully demo project or code. Because all of the Work/Project is from an Company. The only Code I could share was in my question. The only thing I'am doing is to call the 'delegate' methods for the TTTagCollectionView and than set all properties I need. And if I'm setting the .numberOfLines property to '0' on '.horizontal' scroll direction it's always one line.

**Comment by zekunyan** [comment]
> 

In the horizon mode, the `numberOfLines` property can not be set to `0`. Because the `TTTagCollectionView` does not know 'how to calculate the lines with unlimit horizontal scroll width'
