### ISSUE TITLE
Enhancement suggestion for setTagAtIndex

### ISSUE THREAD

**Issue by rjpalermo1** [zekunyan/TTGTagCollectionView#14]
I love this control.  Thank you for making it available.

I've got it doing a lot of what I want it to so far, but there is one enhancement would like to suggest that should make it even more awesome....

[_tagView setTagAtIndex:0 backgroundColor:[UIColor]];
[_tagView setTagAtIndex:0 font:[UIColor]];
[_tagView setTagAtIndex:0 borderColor:[UIColor]];
[_tagView setTagAtIndex:0 borderSizer:[UIColor]];

etc....

In my case, want to add a selectable tag at index 0 that says "Add Tag" in GREEN background to set it apart from other tags.

**Comment by zekunyan** [comment]
The future version will pack all the text tag config together so you can set each tag config separately. It's coming soon.

**Comment by rjpalermo1** [comment]
That is great news!

Can I also suggest adding an example in UITableViewCell to show touchevent on tags?  I have been wrestling this for a few hours now and cannot figure it out.

**Comment by zekunyan** [comment]
You can implement the `TTGTextTagCollectionViewDelegate`'s `- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView didTapTag:(NSString *)tagText atIndex:(NSUInteger)index selected:(BOOL)selected;`  to get the touch event on tag.

**Comment by rjpalermo1** [comment]
Yes, thank you.  I figured it out.  I was using the delegates without success until....

In my tableviewcell.m in the init had to `self.TagView.delegate = self;` then everythign worked as expected.

Great control!  FYI is screen grab - I am using 2 tag views in a single cell.  All that's left is to change the tag background color on the 'Add Tag' and I'm good to go.  Will be watching for updates.

Thank you again....

<img width="369" alt="screen shot 2017-03-02 at 2 09 00 pm" src="https://cloud.githubusercontent.com/assets/7153565/23520576/03e1903c-ff52-11e6-921b-37d114001c62.png">

**Comment by zekunyan** [comment]
@rjpalermo1 The new version 1.5.0 has added the `TTGTextTagConfig` type to help configure tag style separately. You can get more information in the Demo project. :)

**Comment by rjpalermo1** [comment]
AWESOME!  Checking it out later today....
