### ISSUE TITLE
有时会比实际高出一行，滑动后显示正常

### ISSUE THREAD

**Issue by wgbiphone** [zekunyan/TTGTagCollectionView#16]
![simulator screen shot 2017 3 10 5 07 06](https://cloud.githubusercontent.com/assets/1241273/23789109/668ba3f4-05b4-11e7-919b-613d6aa51f8a.png)
![simulator screen shot 2017 3 10 5 07 14](https://cloud.githubusercontent.com/assets/1241273/23789118/69981faa-05b4-11e7-8145-f71d7f91bf5f.png)

**Comment by zekunyan** [comment]
看这个：https://github.com/zekunyan/TTGTagCollectionView/issues/15

**Comment by wgbiphone** [comment]
恩，这就是放上之后的效果

**Comment by wgbiphone** [comment]
<img width="1304" alt="2017-03-10 6 12 36" src="https://cloud.githubusercontent.com/assets/1241273/23791246/383ade76-05bd-11e7-9630-9fe994ead541.png">

**Comment by zekunyan** [comment]
这个可以给个Demo吗？这样看不出来。。。用的最新版？

**Comment by wgbiphone** [comment]
[TTGTagDemo.zip](https://github.com/zekunyan/TTGTagCollectionView/files/834301/TTGTagDemo.zip)

您帮忙看一下，代码用的是github上最新的代码。
![simulator screen shot 2017 3 10 11 21 56](https://cloud.githubusercontent.com/assets/1241273/23800723/69ca9f78-05e8-11e7-9feb-17efcb2382ca.png)

**Comment by zekunyan** [comment]
10.2的一个Bug，加上：
```
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [_tagTableView reloadData];
}
```
之前的issue有说这个
