### ISSUE TITLE
cocopods 最新版本是1.3.0 什么时候更新呀

### ISSUE THREAD

**Issue by aimm** [zekunyan/TTGTagCollectionView#18]

**Comment by zekunyan** [comment]
目前有什么问题吗

**Comment by aimm** [comment]
TTGTagCollectionAlignmentFillByExpandingWidth 这个没法用

**Comment by zekunyan** [comment]
那跟cocopods有啥关系。。。。

**Comment by aimm** [comment]
TTGTagCollectionAlignmentFillByExpandingWidth 在1.4版本才有，cocopods里最新是1.3,这算有关系不

**Comment by zekunyan** [comment]
Cocoapods: http://cocoapods.org/pods/TTGTagCollectionView

Pod search:

```
-> TTGTagCollectionView (1.5.0)
   Show simple text tags or custom tag views in a vertical or horizontal scrollable view.
   pod 'TTGTagCollectionView', '~> 1.5.0'
   - Homepage: https://github.com/zekunyan/TTGTagCollectionView
   - Source:   https://github.com/zekunyan/TTGTagCollectionView.git
   - Versions: 1.5.0, 1.4.1, 1.4.0, 1.3.2, 1.3.0, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.1, 1.0.0, 0.5.0, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.1, 0.1.0 [master repo]
```

**Comment by zekunyan** [comment]
你的源没有更新吧。。。。。。

**Comment by aimm** [comment]
-> TTGTagCollectionView (1.3.0)
   Show simple text tags or custom tag views in a vertical or horizontal
   scrollable view.
   pod 'TTGTagCollectionView', '~> 1.3.0'
   - Homepage: https://github.com/zekunyan/TTGTagCollectionView
   - Source:   https://github.com/zekunyan/TTGTagCollectionView.git
   - Versions: 1.3.0, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.1, 1.0.0, 0.5.0, 0.4.0,
   0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.1, 0.1.0 [master repo]

**Comment by aimm** [comment]
跟你这个一样啊，为啥我这的版本不是最新的呢

**Comment by zekunyan** [comment]
这个。。。更新你的源

**Comment by zekunyan** [comment]
你试试`pod setup`，然后`pod update`

**Comment by aimm** [comment]
好了，更新了源和升级了cocopods

**Comment by zekunyan** [comment]
OK
