### ISSUE TITLE
show a cross button along with tags

### ISSUE THREAD

**Issue by yasirmturk** [zekunyan/TTGTagCollectionView#19]
how to display and use a cross mark button on the right or left side of the tag??

**Comment by zekunyan** [comment]
I don't quite understand. Can you provide a draft picture to show your need ?

**Comment by yasirmturk** [comment]
https://raw.githubusercontent.com/greenchiu/GCTagList/1.3/Screenshot.png

**Comment by zekunyan** [comment]
You can use `TTGTagCollectionView` to make a custom Text tag view.
