### ISSUE TITLE
does it canbe scrolling horizontal custom?

### ISSUE THREAD

**Issue by kency** [zekunyan/TTGTagCollectionView#2]
if not,can you make it work next commit,maybe the view can provide a option likes @property type＝horizontal,   it's very useful. tks

**Comment by zekunyan** [comment]
@kency It's coming soon. :)

**Comment by kency** [comment]
@zekunyan 原来可以讲中文，标签横向滚动应用的类似场景,类似在一个卡片里填加固定frame的scrollView显示单行，数量不定的标签。

**Comment by zekunyan** [comment]
@kency 但是配置参数要指定什么呢？行数？高度？，总得有个垂直方向上的参数限制，这个比较纠结。。。

**Comment by zekunyan** [comment]
@kency 刚发布了新版，增加了水平滚动特性，v1.0.0

**Comment by kency** [comment]
WOW~
