### ISSUE TITLE
Tag background view color on tableview cell highlight and unhighlight

### ISSUE THREAD

**Issue by hanishassim** [zekunyan/TTGTagCollectionView#21]
Hi, please have a look at this tag view inside the table view cell:
![screen shot 2017-04-26 at 2 10 16 am](https://cloud.githubusercontent.com/assets/4571502/25400591/a71c70f2-2a25-11e7-98ac-9a5fc172b4ee.png)
But when I highlight the cell, before release my touch (touch up), the tag view background color hides, and displays this result:
![screen shot 2017-04-26 at 2 10 36 am](https://cloud.githubusercontent.com/assets/4571502/25400710/faca2424-2a25-11e7-84ea-0e0e39a12542.png)

How can make the tag view background color retain its original color?

**Comment by zekunyan** [comment]
Demo code ?

**Comment by zekunyan** [comment]
@hanishassim Can you provide a Demo project ?
