### ISSUE TITLE
abort using in swift

### ISSUE THREAD

**Issue by superk589** [zekunyan/TTGTagCollectionView#24]
你好 大大!
这个库和同类的库对比非常好用
我在Swift中使用时遇到几个无关紧要的小问题或者说小建议
1. 去除参数的 强制解包 "!"
如这里面的TTGTagCollectionView!
```Swift
    func numberOfTags(in tagCollectionView: TTGTagCollectionView!) -> UInt {
        return 1
    }
 ```

2.  能否将大部分方法中的UInt改为Int
UInt直接用在数组的索引很麻烦 还要转换

3. TTGTextTagCollectionView中有一个无关紧要的警告
<img width="1122" alt="qq20170629-0 2x" src="https://user-images.githubusercontent.com/19667784/27668295-e06433ee-5cb2-11e7-8583-a570d4f34702.png">

**Comment by zekunyan** [comment]
1. 这个是OC自动转换成Swift编译器加的，我觉得没有什么不妥
2. 用Uint为了进一步限制变量、参数范围，更加严谨
3. 会改掉，谢谢～

**Comment by mcyj1314** [comment]
这个每一个item的高度都是固定死的吗？ 为什么不暴露属性设置itemSize呢

**Comment by zekunyan** [comment]
@mcyj1314 那就直接用TTGTagCollectionView

**Comment by zekunyan** [comment]
@mcyj1314 有问题新开issue，不要在别人老的issue里面说
