### ISSUE TITLE
用到tableviewCell中，如何按字体长度定义tag宽度，而不是通过屏幕宽度

### ISSUE THREAD

**Issue by jianmu297** [zekunyan/TTGTagCollectionView#25]
如上，参考demo4的代码用在tableviewcell中，比如只有2个tag的时候，他等分preferredMaxLayoutWidth设置每个tag的宽度，但是如何只按照每个tag中text的宽度来设置其宽度呢

**Comment by zekunyan** [comment]
没看懂

**Comment by jianmu297** [comment]
。。比如，当tagview中只有一个元素的时候，tableviewcell demo中会默认tag元素的宽度为preferredMaxLayoutWidth（自适应高度的最大宽度），能否让其宽度为tag元素中的文本宽度加上一定的insert。。

**Comment by jianmu297** [comment]
不好意思，没仔细看wiki，已解决。。。
