### ISSUE TITLE
请问Demo最后一个例子如何scrollable

### ISSUE THREAD

**Issue by wyk111wyk** [zekunyan/TTGTagCollectionView#27]
下载了Demo后打开最后一个例子，放大了字体到35，却发现无法上下移动，请问如何可以让他移动呢？
![simulator screen shot aug 6 2017 16 40 36](https://user-images.githubusercontent.com/8171481/29001792-02e0228a-7ac6-11e7-8726-a5806b2b28a8.png)

**Comment by zekunyan** [comment]
例子的约束设置有问题，已经更新

**Comment by wyk111wyk** [comment]
真记时，谢谢，很好的库
