### ISSUE TITLE
在设置numoflines不等于0时，点击第一个tag， 会引发多次点击回调。

### ISSUE THREAD

**Issue by kevincwt** [zekunyan/TTGTagCollectionView#28]
跟了下代码 ，在TTGTagCollectionView.m中- (void)onTapGesture:(UITapGestureRecognizer *)tapGesture的判断条件CGRectContainsPoint后加一个!tagView.isHidden可解决

**Comment by zekunyan** [comment]
谢谢，可以改下提交一个PR～

**Comment by zekunyan** [comment]
新版已经修复
