### ISSUE TITLE
How to determine the total height of the TTGTagCollectionView?

### ISSUE THREAD

**Issue by sfkewong** [zekunyan/TTGTagCollectionView#3]
I am placing TTGTagCollectionView in a tableviewcell and would like to get the height of the view

**Comment by sfkewong** [comment]
oops... my mistake. Didn't notice there is a delegate method for this. 
func textTagCollectionView(textTagCollectionView: TTGTextTagCollectionView!, updateContentHeight newContentHeight: CGFloat)

Thanks for the awesome library!

**Comment by zekunyan** [comment]
<img width="365" alt="qq20161012-0 2x" src="https://cloud.githubusercontent.com/assets/5687881/19308691/8ea2bc9a-90b3-11e6-9942-d388264eec38.png">
You can find it in the Example. :)

**Comment by Sadmansamee** [comment]
@zekunyan  I could not find this example(Use in tableviewcell).

**Comment by zekunyan** [comment]
@Sadmansamee Download the project and open "Exampl->TTGTagCollectionView.xcworkspace". Build and run the example and you can find it.
