### ISSUE TITLE
当tagView在另一个collectionView,tableview,scrollView里时，点击状态栏返回顶部失效

### ISSUE THREAD

**Issue by kency** [zekunyan/TTGTagCollectionView#32]
我把textTagView放在了业务collectionView卡片列表的collectionViewCell里，在滑动到可见cell有tagView并有tag的时候iOS的点击状态栏返回顶部失效。滑动到可见部分的cell里tagView.hidden=YES的时候，就可以返回//ps用的当前最新版本 ,这个问题从第一版就存在,tableview已测，一样
target IOS8.0 xcode8.33 测试机IOS8.4

**Comment by zekunyan** [comment]
有代码吗

**Comment by kency** [comment]
有，拿出来放到这里了https://github.com/kency/CVUItagsScrollView

**Comment by LxwYl** [comment]
如何计算整体的高度
