### ISSUE TITLE
问题修复

### ISSUE THREAD

**Issue by songliguo** [zekunyan/TTGTagCollectionView#35]
您好，你的框架在滚动之后无法保存点击状态，可以更新修复一下吗？

**Comment by zekunyan** [comment]
状态是要自己保存的，我这个只是UI控件，不是Bug，请研究清楚再用

**Comment by songliguo** [comment]
嗯，我没说是Bug，我的意思是是否可以提供根据数据更新状态的接口？我看现在的只有是否可点击以及点击了哪一个，并且赋值参数是添加一个字符串数组。是否可以提供存放model的接口，或者定义一个model协议，遵守协议的可以添加到数据源，内部根据模型的select属性标记label从而实现保存状态？

**Comment by zekunyan** [comment]
可以使用TTGTextTagCollectionViewDelegate来获取每个Tag的状态

```
@protocol TTGTextTagCollectionViewDelegate <NSObject>
@optional
- (BOOL)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView canTapTag:(NSString *)tagText atIndex:(NSUInteger)index currentSelected:(BOOL)currentSelected;

- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView didTapTag:(NSString *)tagText atIndex:(NSUInteger)index selected:(BOOL)selected;

- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView updateContentSize:(CGSize)contentSize;
@end
```

**Comment by zekunyan** [comment]
主动设置：

```
- (void)setTagAtIndex:(NSUInteger)index selected:(BOOL)selected;
```

就是不想做的太重，所以没有搞数据绑定之类的

**Comment by zekunyan** [comment]
默认添加没有selected，用户点击可以用delegate回调获知，主动设置可以通过setTagAtIndex:selected:方法，总体状态外部保存配置

**Comment by songliguo** [comment]
通过setTagAtIndex:selected:方法主动设置，之后滑动界面数据会回滚到最初状态，我目前的需求是tableview的三个section，每一个都是使用的您的Tag。总体状态外部保存配置是怎么操作的，可以指点一下小弟吗？十分感谢...

**Comment by zekunyan** [comment]
你用在cell里面的？cell重用的时候肯定不行啊=。=，要自己每次重用都设置

**Comment by songliguo** [comment]
哈哈，所以就比较恶心了...我在想其他办法吧，谢谢
