### ISSUE TITLE
How can I select Tag ID ?

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [zekunyan/TTGTagCollectionView#36]
Hello, It's great! Everything working is great displayed array names from server. now, In array Names, each name having different unique ID. How  to get ID when i was selected name in collection ? 
JSON:  
`{
            "stid": "720",
            "name": "VISHALI"
        },
        {
            "stid": "732",
            "name": "RAJESH"
        },
        `

Please help me.

**Comment by zekunyan** [comment]
```
@protocol TTGTextTagCollectionViewDelegate <NSObject>
@optional
- (BOOL)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView canTapTag:(NSString *)tagText atIndex:(NSUInteger)index currentSelected:(BOOL)currentSelected;

- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView didTapTag:(NSString *)tagText atIndex:(NSUInteger)index selected:(BOOL)selected;

- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView updateContentSize:(CGSize)contentSize;
@end
```
Use the delegate to monitor user tap action and get your ID by `index`.

**Comment by IOSDeveloperProgrammer** [comment]
@zekunyan Yeah,  I using swift 3. I'm getting selected indexpath not 'studentID'. I'm displayed names correctly. How can i pass student id it. 
My code:
` func textTagCollectionView(_ textTagCollectionView: TTGTextTagCollectionView!, didTapTag tagText: String!, at index: UInt, selected: Bool) {
        print("studentName:%@", tagText)
        print("studid:%@", index)

    }` 
saving array:
` self.tagCollectionView.addTags(self.studentListName)`
