### ISSUE TITLE
手势滚动性能问题

### ISSUE THREAD

**Issue by yizzuide** [zekunyan/TTGTagCollectionView#39]
在iPhone 5s为iOS 11系统上运行滚动时，会出现手势短暂失效的问题，可能与卡顿有关

**Comment by zekunyan** [comment]
示例代码？Demo？场景？

**Comment by yizzuide** [comment]
@zekunyan 经测试发现是iPhone 5s升级到iOS 11的问题，因为整个系统的UI都有这种卡顿情况
