### ISSUE TITLE
Associated data when using TTGTextTagCollectionView

### ISSUE THREAD

**Issue by eliburke** [zekunyan/TTGTagCollectionView#41]
This is a great framework, and TTGTextTagCollectionView provides just about everything I need... but it took a while to figure out how to associate separate data with the tags. 

Because I am adding tags from a multi-section tableview, I have to store the selected tags in a separate array that is indexed the same as the tags. If I want to remove a tag when it is tapped, and de-select the row in the table view, I do the following:

````
        tagCollectionView.removeTag(at: index)
        let tappedContact = currentSelected.remove(at: Int(index))
    
        var section = 0
        for contactSection in contactSections {
            var row = 0
            for contact in contactSection {
                if contact == tappedContact {
                    let ip = IndexPath(row: row, section: section)
                    contactTable.deselectRow(at: ip, animated: false)
                    updateHeaderView()
                    return
                }
                row += 1
            }
            section += 1
        }
````

This is ok, but it would be so great if addTag/insertTag took an additional parameter for a void*/Any/AnyObject. The same parameter would be returned by didTapTag. Alternatively, if addTag/insertTag returned the tag, and TTGTagLabel was made a public class, we could attach the data ourselves. 

If you are interested, I could submit a PR. My Objective C is rusty but I think I can still manage.

**Comment by zekunyan** [comment]
The latest version's TTGTextTagLabel definition is:

```
@interface TTGTextTagLabel : UIView
@property (nonatomic, strong) TTGTextTagConfig *config;
@property (nonatomic, strong) GradientLabel *label;
@property (assign, nonatomic) BOOL selected;
@end
```

So each tag label  is binding a `TTGTextTagConfig` object which defines the tag's  style. The next version i want to add a `NSObject` property to the `TTGTextTagConfig` class. So you can store your tag's additional parameter in the config object. And then use the `- (void)addTag:(NSString *)tag withConfig:(TTGTextTagConfig *)config;` method to add the tag.

**Comment by zekunyan** [comment]
@eliburke 

The new version 1.9.0 add a new property in the `TTGTextTagConfig `

```
// Extra data. You can use this to bind any object you want to each tag.
@property (nonatomic, strong) NSObject *extraData;
```

And update the methods in the `TTGTextTagCollectionViewDelegate `

```
@protocol TTGTextTagCollectionViewDelegate <NSObject>
@optional
- (BOOL)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView
                    canTapTag:(NSString *)tagText
                      atIndex:(NSUInteger)index
              currentSelected:(BOOL)currentSelected
                    tagConfig:(TTGTextTagConfig *)config;

- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView
                    didTapTag:(NSString *)tagText
                      atIndex:(NSUInteger)index
                     selected:(BOOL)selected
                    tagConfig:(TTGTextTagConfig *)config;

- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView
            updateContentSize:(CGSize)contentSize;
@end
```

Now you can add your tag with additional parameter to the `extraData` and add tag by using the method: 

```
- (void)addTag:(NSString *)tag withConfig:
``` 

And when tap on the tag, the callback method in `TTGTextTagCollectionViewDelegate` will pass the right config to you :)

**Comment by eliburke** [comment]
Fantastic. Thanks for the quick update! 👍
