### ISSUE TITLE
数量

### ISSUE THREAD

**Issue by Yu-Tuo** [zekunyan/TTGTagCollectionView#42]
你好，请问可以设置只点击一个

**Comment by zekunyan** [comment]
@Yu-Tuo delegate有回调，需要自己判断

**Comment by Yu-Tuo** [comment]
我看到有个默认配置里有一个limit属性，这个可以。但是我的需求是点击另一个，以前点击的变为不点击

**Comment by zekunyan** [comment]
@Yu-Tuo 这个要自己控制逻辑，看看API可以代码控制某个tag选中、取消选中的
