### ISSUE TITLE
高度计算有问题

### ISSUE THREAD

**Issue by yuzhongxingke** [zekunyan/TTGTagCollectionView#43]
由于其它布局原因，不能使用autolayout布局，我是先把控件放到xib上，然后使用下面方法：
[_tagCollectionView addTags:tags];
[_tagCollectionView reload];
//再此获取到contentSize,然后重置布局高度
 _tagHeightLayoutConstraint.constant = _tagCollectionView.contentSize.height;

备注：发现contentSize比实际的要高很多，如图，红色框是多出来的额外空白高度
![image](https://user-images.githubusercontent.com/4360943/38158669-bb9af11e-34cb-11e8-94bf-a8e9c4c4ed0a.png)

**Comment by zekunyan** [comment]
@yuzhongxingke 

```
// Manual content height
// Default = NO, set will update content
@property (nonatomic, assign) BOOL manualCalculateHeight;
// Default = 0, set will update content
@property (nonatomic, assign) CGFloat preferredMaxLayoutWidth;
```

**Comment by yuzhongxingke** [comment]
@zekunyan 

`_tagCollectionView.manualCalculateHeight = YES;
    _tagCollectionView.preferredMaxLayoutWidth = [UIScreen mainScreen].bounds.size.width;
    [_tagCollectionView addTags:tags];
    _heightLayoutConstraint.constant = _tagCollectionView.contentSize.height;`

这样是可以的，谢谢啦！
