### ISSUE TITLE
Vertically Center while scroll direction is Horizontal

### ISSUE THREAD

**Issue by johanesadika** [zekunyan/TTGTagCollectionView#45]
Hello, is it possible to have vertically center but the scroll direction is horizontal?
Currently, it is always left alignment when scroll direction is horizontal.
Thank you

**Comment by ankit-betterbutter** [comment]
Where you able to achieve this?

**Comment by ankit-betterbutter** [comment]
I also need to make tag view in which the 
> tag are scrolled in horizontal direction only
> single lined
> must be in the center to the view height
Please help !!

**Comment by zekunyan** [comment]
@johanesadika @ankit-betterbutter  Can you guys give me some draft image ? I don't know your probloms. :)
