### ISSUE TITLE
Add a cancel, close, selected to the tags

### ISSUE THREAD

**Issue by ankit-betterbutter** [zekunyan/TTGTagCollectionView#46]
![screen shot 2018-05-10 at 1 53 17 pm](https://user-images.githubusercontent.com/23396811/39860053-88408312-5459-11e8-892f-889584ffe735.png)

PFA for reference>

Can something like this be added to customization

**Comment by muhammad-zohaib-ehsan** [comment]
A tag is represented by string. Perhaps you can use unicode character for the cross symbol. Then it will behave like the intended behaviour.

**Comment by zekunyan** [comment]
You can use the `TTGTagCollectionView` class to make your own Tag view.

**Comment by zekunyan** [comment]
Use the `TTGTagCollectionView ` and make your own `TagView` by implementing the `delegate` and `dataSource` of the `TTGTagCollectionView `.

**Comment by zekunyan** [comment]
I will add `NSAttributedString` to the `TTGTextTagCollectionView` in the next version. Then you can add the `X` close image in the attributed string by using the `NSTextAttachment `.
