### ISSUE TITLE
ContentInset strange behaviour

### ISSUE THREAD

**Issue by jdanthinne** [zekunyan/TTGTagCollectionView#47]
If I don't touch the default settings for a TTGTagCollectionView, it seems that a default `contentInset` of 2 pixels is there all around the scrollView.

<img width="864" alt="capture d ecran 2018-06-06 a 17 22 36" src="https://user-images.githubusercontent.com/485107/41048595-5f1a1438-69af-11e8-94ab-a541df02b055.png">

I've tried to remove it by setting a `contentInset(top:0, left:0, bottom:0, right:0)`, but then, the content seems clipped at the bottom where there's more than one line of tags… is it normal (I don't think so)?

<img width="785" alt="capture d ecran 2018-06-06 a 17 26 49" src="https://user-images.githubusercontent.com/485107/41048602-608dfc4e-69af-11e8-8215-59a7b08d8212.png">

**Comment by jdanthinne** [comment]
Difficult… it comes from a very very large base code.
I've tried to modify your examples, but I'm only proficient in Swift, so I couldn't. Perhaps the example with TableView cells could be updated or duplicated to have an example with TTGTagViewCollections instead of TTGTextTagViewCollections in each cell?

**Comment by zekunyan** [comment]
@jdanthinne 
I check your screenshot again and i found that maybe the problem is the "height of cell" calculated wrong. 
To calculate the cell height right, you can set the `manualCalculateHeight` to `true` and  config `preferredMaxLayoutWidth` to a suitable width just like UILabel and try again.

**Comment by jdanthinne** [comment]
That was it! Thanks a lot.
