### ISSUE TITLE
Allow configuration of which corners to round

### ISSUE THREAD

**Issue by twof** [zekunyan/TTGTagCollectionView#48]
Sometimes a user may only want the bottom right and bottom left corners rounded. For example

<img width="351" alt="screen shot 2018-06-13 at 1 37 37 pm" src="https://user-images.githubusercontent.com/5561501/41376752-01b4d89a-6f0f-11e8-967b-ccc8df7e0415.png">

In Swift that may look something like

```swift
config.roundedCorners = [UIRectCorner.bottomLeft, UIRectCorner.bottomRight]
```

**Comment by twof** [comment]
I have something working on my branch that has an API like this if you want me to submit a PR with it, but I'd prefer the above API

```objective c
    config.roundBottomRight = true;
    config.roundBottomLeft = true;
    config.roundTopRight = false;
    config.roundTopLeft = false;
```

I'm not familiar enough with Objective C to create it though

**Comment by zekunyan** [comment]
You can do it ! :)

**Comment by twof** [comment]
Sweet!
https://github.com/zekunyan/TTGTagCollectionView/pull/49

**Comment by twof** [comment]
Resolved after merge. Thanks for accepting the PR :)

**Comment by zekunyan** [comment]
Great work. Thank you. ~
