### ISSUE TITLE
uitablviewcell 中的tagview点击无效

### ISSUE THREAD

**Issue by MrCaiWH** [zekunyan/TTGTagCollectionView#52]
我的tagview在uitableviewcell中，因为它只是起到了一个展示的作用，无需要点击功能，因此我设置了属性enableTagSelection = NO，可是我现在发现，当我选中这个cell的时候，如果点击tagvie这块区域，无法被选中，点击无效，求解决，期待你的回复，谢谢

**Comment by zekunyan** [comment]
设置`userInteractionEnabled = NO`

**Comment by MrCaiWH** [comment]
谢谢

**Comment by AnswerX** [comment]
你好，我在tableViewcell里设置的一个自定义的tagview,点击事件不响应
`- (void)tagCollectionView:(TTGTagCollectionView *)tagCollectionView didSelectTag:(UIView *)tagView atIndex:(NSUInteger)index`
demo里的example2就可以，代理走到`if (CGRectContainsPoint(tagView.frame, tapPoint) && !tagView.isHidden)` 就不走了，判断frame的问题吗
另外设置`userInteractionEnabled = NO` 是设置哪个视图，我设置cell不行

**Comment by zekunyan** [comment]
@AnswerX 有Demo？

**Comment by AnswerX** [comment]
`- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier {
    self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
    if (self) {
        [self createUI];
    }
    return self;
}

- (void)createUI{
    [self.contentView addSubview:self.tagCollectionView];
    [self.tagCollectionView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.contentView);
    }];
}

- (void)setModel:(DiscoverCategories *)model{
    _model = model;
    [self.tagViews removeAllObjects];
    
    for (DiscoverCategories *newModel in model.childrens) {
        [self.tagViews addObject:[self newButtonWithTitle:newModel.name]];
    }
    self.pointY = self.tagCollectionView.contentSize.height;
    [self.tagCollectionView reload];

}

- (UIButton *)newButtonWithTitle:(NSString *)title {
    
    UIButton *button =[UIButton buttonWithType:UIButtonTypeCustom];
//    NSMutableAttributedString *str = [[NSMutableAttributedString alloc] initWithString:title attributes:@{NSKernAttributeName:@(-0.15)}];
//    [button setAttributedTitle:str forState:UIControlStateNormal];
    [button setTitle:title forState:UIControlStateNormal];
    [button setTitleColor:[UIColor color333333] forState:UIControlStateNormal];
    button.titleLabel.font = [UIFont systemFontOfSize:14];
    [button setBackgroundColor:[UIColor color234Gray]];
    [button setImage:[UIImage imageNamed:@"icTrendingUp"] forState:UIControlStateNormal];
    [button sizeToFit];

    CGRect frame = button.frame;
    frame.size.width +=25;
    frame.size.height =35;
    button.frame = frame;
    [button setTitleColor:[UIColor whiteColor] forState:UIControlStateSelected];
    button.titleEdgeInsets = UIEdgeInsetsMake(0, 5, 0, 0);
    button.imageEdgeInsets = UIEdgeInsetsMake(0, -5, 0, 0);
    button.layer.masksToBounds = YES;
    button.layer.cornerRadius = button.frame.size.height *0.5;
    
    [button addTarget:self action:@selector(btnClicked:) forControlEvents:UIControlEventTouchUpInside];
    return button;
}

#pragma mark - TTGTagCollectionViewDelegate
- (CGSize)tagCollectionView:(TTGTagCollectionView *)tagCollectionView sizeForTagAtIndex:(NSUInteger)index{
//    NSLog(@"%@",NSStringFromCGSize(self.tagViews[index].frame.size));
    return self.tagViews[index].frame.size;
}

- (void)tagCollectionView:(TTGTagCollectionView *)tagCollectionView didSelectTag:(UIView *)tagView atIndex:(NSUInteger)index{
    

}

#pragma mark - TTGTagCollectionViewDataSource
- (NSUInteger)numberOfTagsInTagCollectionView:(TTGTagCollectionView *)tagCollectionView{
    return self.tagViews.count;
}

- (UIView *)tagCollectionView:(TTGTagCollectionView *)tagCollectionView tagViewForIndex:(NSUInteger)index{
    return self.tagViews[index];
}
- (void)btnClicked:(UIButton *)btn{
    NSLog(@"点击了按钮");
}
#pragma mark - get
- (TTGTagCollectionView *)tagCollectionView{
    if (!_tagCollectionView) {
        
        _tagCollectionView = [[TTGTagCollectionView alloc] initWithFrame:self.contentView.frame];
        _tagCollectionView.contentInset = UIEdgeInsetsMake(5, 15, 5, 5);
        _tagCollectionView.verticalSpacing = 10;
        _tagCollectionView.horizontalSpacing = 10;
        _tagCollectionView.alignment = TTGTagCollectionAlignmentLeft;
        _tagCollectionView.manualCalculateHeight = YES;
        _tagCollectionView.preferredMaxLayoutWidth = DeviceWidth;
        _tagCollectionView.delegate = self;
        _tagCollectionView.dataSource = self;
    }
    return _tagCollectionView;
}
- (NSMutableArray<UIView *> *)tagViews{
    if (!_tagViews) {
        _tagViews = [NSMutableArray new];
    }
    return _tagViews;
}`

**Comment by AnswerX** [comment]
> @AnswerX 有Demo？
在添加进containerView 的自定义视图，不响应containerView的手势
```
- (void)onTapGesture:(UITapGestureRecognizer *)tapGesture
```
@zekunyan
