### ISSUE TITLE
cell的点击事件用代理怎么使用 例如demo4怎么监听到点击的tags

### ISSUE THREAD

**Issue by DexSinis** [zekunyan/TTGTagCollectionView#55]
cell的点击事件用代理怎么使用 例如demo4怎么监听到点击的tags

**Comment by DexSinis** [comment]
但是我们两个工程师把文件挪到新的工程，点击cell的时候没监听到事件哦，方便加一下我么，我项目比较急343731621  微信，谢谢，麻烦你了

**Comment by zekunyan** [comment]
目前不行的
