### ISSUE TITLE
UITableViewAutomaticDimension does not work for UITableViewCell in viewDidAppear

### ISSUE THREAD

**Issue by Terens777** [zekunyan/TTGTagCollectionView#57]
In my custom cell I initialize all the configs for the view tags, I do it in awakeFromNib, if I there do the default array with the data then UITableViewAutomaticDemension works fine, if i loading data from Api after reload in viewDidAppear UITableViewAutomaticDemension for tableCell not work, what should I do?

**Comment by zekunyan** [comment]
```
// Manual content height
// Default = NO, set will update content
@property (nonatomic, assign) BOOL manualCalculateHeight;
// Default = 0, set will update content
@property (nonatomic, assign) CGFloat preferredMaxLayoutWidth;
```
