### ISSUE TITLE
不能应用在tablviewCell里面吗?

### ISSUE THREAD

**Issue by xialisuper** [zekunyan/TTGTagCollectionView#58]
请教:
我想在cell里放5个uiview
但是不会自动刷新cell的高度 如何处理?

`- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier {
       ....
       TTGTagCollectionView * collectionView = [[TTGTagCollectionView alloc] init];
        collectionView.translatesAutoresizingMaskIntoConstraints = NO;
        collectionView.dataSource = self;
        collectionView.delegate = self;
        self.collecitonView = collectionView;
        [self.contentView addSubview:videoCollectionView];
}

- (NSUInteger)numberOfTagsInTagCollectionView:(TTGTagCollectionView *)tagCollectionView {
    return 5;
}

- (UIView *)tagCollectionView:(TTGTagCollectionView *)tagCollectionView tagViewForIndex:(NSUInteger)index {
    UIView *view = [UIView new];
//    view.size = CGSizeMake(57, 57);
    view.backgroundColor = [UIColor redColor];
    return view;
}
- (void)tagCollectionView:(TTGTagCollectionView *)tagCollectionView updateContentSize:(CGSize)contentSize {
    NSLog(@"%@", NSStringFromCGSize(contentSize));

}

- (CGSize)tagCollectionView:(TTGTagCollectionView *)tagCollectionView sizeForTagAtIndex:(NSUInteger)index {
    return CGSizeMake(57, 57);
}

//在设置数据的时候刷新UI
- (void)setModel:(XXModel *)model {
    _model = model;
    [self.collectionView reload];
}

`

我应该怎么处理这里呢?

**Comment by zekunyan** [comment]
看Demo
