### ISSUE TITLE
accessibilityIdentifier on tags.

### ISSUE THREAD

**Issue by jontelang** [zekunyan/TTGTagCollectionView#59]
It would be nice to be able to set accessibilityIdentifier on the tags easily. If I want to add this myself, do you have a recommended place to do so?

I looked at the code briefly and I might be able to add a `tagAccessibilityIdentifier` in the config, then set that identifier when a tag is being displayed. As tags are essentially buttons, the accessibility property `isSelected` is also needed.

I use accesibility identifiers for UI testing to be able to see which items are selected and which are not. unfortunately this tool does not seem to easily support this right now.

**Comment by jontelang** [comment]
Sure, I will work on it within this week.

**Comment by wsbuser** [comment]
Is this feature working now?. It will definitely be very usefull.

**Comment by jontelang** [comment]
@wsbuser I did not get time to work on this, just as an FYI.

**Comment by faraz-mayd** [comment]
Hi jontelang,

Have you added the accessibilityIdentifier for it? Thanks..

**Comment by zekunyan** [comment]
I will add this feature to the next version today.

**Comment by zekunyan** [comment]
The new version `2.4.1` released. Now you can setup the `accessibilityX` property in TTGTextTag instance. 

```
// Auto set accessibilityLabel value
tag.enableAutoDetectAccessibility = YES;

// Manual
tag.isAccessibilityElement = YES;
tag.accessibilityLabel = text;
tag.accessibilityIdentifier = [NSString stringWithFormat:@"identifier: %@", text];
tag.accessibilityHint = [NSString stringWithFormat:@"hint: %@", text];
tag.accessibilityValue = [NSString stringWithFormat:@"value: %@", text];
```

**Comment by faraz-mayd** [comment]
Great thanks..
