### ISSUE TITLE
横向瀑布流滑动时出现重叠现象。

### ISSUE THREAD

**Issue by wayne798** [zekunyan/TTGTagCollectionView#6]
在使用横向的瀑布流时，发现会有重叠现象，后面的数据跑到前面来了。

**Comment by zekunyan** [comment]
怎么用的？贴下代码？

**Comment by wayne798** [comment]
附件里面有代码啊，我创建了个数组，tag2，使用那个数组就会出现，方便的话可以加qq交流吗，496577309






在 2016-12-12 12:37:53，"zekunyan" <notifications@github.com> 写道：


怎么用的？贴下代码？

**Comment by wayne798** [comment]
我给你发163邮箱了，邮件里面附件是使用代码。
跟现实内容有关系，我使用下面这个数组显示时，会重叠，给你发的163邮箱里面也有截图
NSArray *tags2 = @[@"❤️❤️❤️❤️❤️❤️❤️❤️",
    @"法兰克福这场表现棒棒哒~~",
    @"最后十分钟了，法兰克福挺住！",
    @"足球通用",
    @"O(∩_∩)O哈！O(∩_∩)O哈！O(∩_∩)O哈！",
    @"?_?什么，呀呀呀，厉害，word哥*&……%￥#@！",
    @"啦啦啦，喜欢~~~~~~~?❤️?",
    @"你好呀，good~<(￣︶￣)↗[GO!]",
    @"↖(^ω^)↗↖(^ω^)↗??❤️?",
    @"1",
    @"啦啦啦~\(≧▽≦)/~啦啦啦",
    @"哇咔咔哇咔咔哇咔咔哇咔咔哇咔咔哇咔咔哇卡"];

**Comment by wayne798** [comment]
找到了一种最简单的必现方式：
修改TTGExample5ViewController.m 如下：
- (void)viewDidLoad {
    [super viewDidLoad];
    
    NSArray *tags = @[@"AutoLayout", @"dynamically", @"calculates", @"the", @"size", @"and", @"position",
                      @"of", @"all", @"the", @"views", @"in", @"your", @"view", @"hierarchy", @"based",
                      @"on", @"constraints", @"placed", @"on", @"those", @"views"];
    NSArray *tags2 = @[@"❤️❤️❤️❤️❤️❤️❤️❤️",
                       @"法兰克福这场表现棒棒哒~~",
                       @"最后十分钟了，法兰克福挺住！",
                       @"足球通用",
                       @"?_?什么，呀呀呀，厉害，word哥*&……%￥#@！",
                       @"啦啦啦，喜欢~~~~~~~?❤️?",
                       @"你好呀，good~<(￣︶￣)↗[GO!]",
                       @"↖(^ω^)↗↖(^ω^)↗??❤️?",
                       @"1",
                       @"啦啦啦~\(≧▽≦)/~啦啦啦",
                       @"哇咔咔哇咔咔哇咔咔哇咔咔哇咔咔哇咔咔哇卡"];
    _oneLineTagView.scrollDirection = TTGTagCollectionScrollDirectionHorizontal;
    _twoLineTagView.scrollDirection = TTGTagCollectionScrollDirectionHorizontal;
    _threeLineTagView.scrollDirection = TTGTagCollectionScrollDirectionHorizontal;

    _oneLineTagView.numberOfLines = 1;
    _twoLineTagView.numberOfLines = 2;
    _threeLineTagView.numberOfLines = 3;
    _threeLineTagView.tagTextFont = [UIFont systemFontOfSize:15];

    [_oneLineTagView addTags:tags];
    [_twoLineTagView addTags:tags];
    [_threeLineTagView addTags:tags2];
}

使用tag1不会重叠，使用tag2并且设置font大小为15时必现。
