### ISSUE TITLE
I need single selection

### ISSUE THREAD

**Issue by syedrazackimran** [zekunyan/TTGTagCollectionView#61]
hi hello, 
i would like to change multi-selection to a single selection. could you help me to change,
kindly do needfully

**Comment by zekunyan** [comment]
You can use the delegate to control the selection.

**Comment by syedrazackimran** [comment]
thanks, I already resolved it by using an index. thanks for your support

**Comment by Beautistar** [comment]
Which delegate method is used? @syedrazackimran Can you show me code example?
