### ISSUE TITLE
富文本的支持

### ISSUE THREAD

**Issue by czwpro** [zekunyan/TTGTagCollectionView#63]
能否添加对富文本的支持

**Comment by zekunyan** [comment]
attributedString ?

**Comment by czwpro** [comment]
是的，这还是比较常见的，至少在我的项目中就出现了几次，当然一般情况下只会是文字颜色上的区别，很少会出现字体大小不同的标签样式，所以我觉得可以考虑一下

**Comment by zekunyan** [comment]
OK，下个版本就会考虑
