### ISSUE TITLE
大佬能弄个单选的标签demo吗？

### ISSUE THREAD

**Issue by sjxt** [zekunyan/TTGTagCollectionView#67]

**Comment by xuuhan** [comment]
if (self.ChoiceType == ChoiceTypeOne) {
        if (self.tagView.allSelectedTags.count != 0 && _lastIndex != index) {
            [self.tagView setTagAtIndex:_lastIndex selected:NO];
        }
        _lastIndex = index;
    }

**Comment by sjxt** [comment]
多谢
