### ISSUE TITLE
problem in tableview cell

### ISSUE THREAD

**Issue by rakii** [zekunyan/TTGTagCollectionView#7]
Getting more of extra space in tableview cells tagview.

 Given constraints are top to "add tags label", leading, trailing, bottom, and height greater than or equal to 30

 tagView.extraSpace = CGSize(width:20,height:25)

in layoutSubviews,

tagView.tagCornerRadius = 20
tagView.clipsToBounds = true

<img width="319" alt="screen shot 2017-01-15 at 1 43 20 pm" src="https://cloud.githubusercontent.com/assets/7426603/21961178/b514d632-db28-11e6-8238-dc24725d0979.png">

**Comment by zekunyan** [comment]
The `tagView.extraSpace` means the more width and height added to each tag cell. I don't quiet understand the problem.

**Comment by rakii** [comment]
@zekunyan To be specific, am facing an issue of getting extra white space after the tagsview when used in tableview cell.
![screen shot 2017-01-16 at 4 45 00 pm](https://cloud.githubusercontent.com/assets/7426603/21980938/288ac242-dc0b-11e6-9307-af387a27c516.png)

**Comment by zekunyan** [comment]
Maybe the tableViewCell height wrong.

**Comment by rakii** [comment]
its dynamic cell height as the tags are dynamic, based on entering tags in another view controller, this is loaded.

`func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableViewAutomaticDimension
    }
`

**Comment by zekunyan** [comment]
The example project: 
![image](https://cloud.githubusercontent.com/assets/5687881/21987221/94f3f8ea-dc3d-11e6-9323-ac7cca5511d6.png)

**Comment by rakii** [comment]
yeah checked that. Will get back with exact issue. Thanks @zekunyan

**Comment by rakii** [comment]
Fixed it its due to constraints and cliptobounds.
Also how to make the tags corner radius so that each should show certain corner radius but not complete circle, should be dynamic depending on the text of the tag @zekunyan

**Comment by zekunyan** [comment]
For now it can only depending on the text of the tag. Maybe you can make custom text tags view by TTGTagCollectionView. :)

**Comment by zekunyan** [comment]
And maybe you can set larger `extraSpace` for text tag to expand the tag. That may fix the 'circle' tag problem.

**Comment by rakii** [comment]
yeah. Did that already. Want to know if there is any another way around. Cool Thanks.
