### ISSUE TITLE
怎样做到在只显示一行里，把没全部展示出来的标签不显示？ 就是只展示文字完全显示出来的标签？

### ISSUE THREAD

**Issue by Climb0516** [zekunyan/TTGTagCollectionView#72]
请问：怎样做到在只显示一行里，把没全部展示出来的标签不显示？ 
就是只展示文字完全显示出来的标签？没全部展示出来的标签不显示呢？

**Comment by zekunyan** [comment]
示意图？

**Comment by Climb0516** [comment]
![](https://ws1.sinaimg.cn/large/006tNc79ly1fzfhqzx5maj30c6032t96.jpg)
如上图，因为红色框部分已经显示不全，所以从红色框部分开始不在显示后面的标签

**Comment by zekunyan** [comment]
@Climb0516 就是按宽度展示可展示完全的？
