### ISSUE TITLE
`TTGTextTagLabel`  finalSize calclulation issue with extraSize

### ISSUE THREAD

**Issue by wving5** [zekunyan/TTGTagCollectionView#73]
https://github.com/zekunyan/TTGTagCollectionView/blob/4aec6da7cfa781eb5e981d38b008490a0f390c0e/TTGTagCollectionView/Classes/TTGTextTagCollectionView.m#L214

Use `size.width < self.config.minWidth`  NOT `finalSize.width < self.config.minWidth` make `_config.extraSpace.width` invalid ( finalSize will be reset to `minWidth`),  cuz `config.extraSpace` was added to `finalSize` before comparison.  

In my understanding, `minWidth` should be used to **increase** NOT **decrease** width ...

**Comment by zekunyan** [comment]
@wving5 You can make a Pull Request 👍

**Comment by zekunyan** [comment]
@wving5 I fixed this in the 1.11.1 version.

**Comment by wving5** [comment]
Thx! You are really a nice guy ~  >.<
