### ISSUE TITLE
如何能实现单选?

### ISSUE THREAD

**Issue by heqikang** [zekunyan/TTGTagCollectionView#76]
如题, 只能选择一项,选中的那一项高亮,其他变为默认状态

**Comment by hw20101101** [comment]
我刚碰到这个需求：

```
/**
 上一次选中的 tag index
 */
@property (assign, nonatomic) NSInteger lastSelectedIndex;
```

```

- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView
                    didTapTag:(NSString *)tagText
                      atIndex:(NSUInteger)index
                     selected:(BOOL)selected
                    tagConfig:(TTGTextTagConfig *)config{
 
    //上一次选中 有值，并且跟本次选中的 index 不同
    if (self.lastSelectedIndex != -1 && self.lastSelectedIndex != index) {
        //取消上一次选中
        [textTagCollectionView setTagAtIndex:self.lastSelectedIndex selected:NO];
    }
    
    self.lastSelectedIndex = index; 
}

```

**Comment by zekunyan** [comment]
这个需要自己控制

**Comment by Just013** [comment]
补充一下二楼的，本次更新：取消返选效果。
- (void)textTagCollectionView:(TTGTextTagCollectionView *)textTagCollectionView
                    didTapTag:(NSString *)tagText
                      atIndex:(NSUInteger)index
                     selected:(BOOL)selected
                    tagConfig:(TTGTextTagConfig *)config {
    //上一次选中 有值，并且跟本次选中的 index 不同
    if (self.lastSelectedIndex != -1 && self.lastSelectedIndex != index) {
        //取消上一次选中
        [textTagCollectionView setTagAtIndex:self.lastSelectedIndex selected:NO];
    }
    if (self.lastSelectedIndex == index) {
        //取消返选效果
        [textTagCollectionView setTagAtIndex:self.lastSelectedIndex selected:YES];
    }
    
    self.lastSelectedIndex = index;
}
