### ISSUE TITLE
alignment 使用 fillByExpandingWidth 展示问题

### ISSUE THREAD

**Issue by MorningStarJ** [zekunyan/TTGTagCollectionView#77]
![88B478CC1C8B0147586BBC310421CF5B](https://user-images.githubusercontent.com/15356218/56654565-fd3f8d80-66c2-11e9-9f0e-e8ecdbd32b0e.png)
alignment 使用 fillByExpandingWidth 变成了这样，不应该是一行展示么，numberofline 我没设置
点后展示恢复正常，但高度还是2行的高度，
![3C2966BEC0C2F5A7BA794CE757F4A721](https://user-images.githubusercontent.com/15356218/56654739-64f5d880-66c3-11e9-93ee-a23ede9c8b28.jpg)

**Comment by zekunyan** [comment]
Demo 代码有么

**Comment by MorningStarJ** [comment]
> Demo 代码有么

https://github.com/MorningStarJ/TestTTGTagCollectionView.git

**Comment by MorningStarJ** [comment]
> Demo 代码有么

暂时解决办法是将tagview 放在stackview上，再把stackview放在stackview上就正常了，希望作者可以看下放在Stackview上高度不准以及展示不对的问题

**Comment by zekunyan** [comment]
@MorningStarJ 这个不是问题，iOS的设计就是这样，viewDidLoad的时候拿不到真实宽度的，只有屏幕宽度才是对的，view都是不对的，所以Demo里面preferredMaxLayoutWidth设置的值不对。
```
tagView.preferredMaxLayoutWidth = UIScreen.main.bounds.size.width
```

**Comment by zekunyan** [comment]
@MorningStarJ 建议你去研究下Controller、Autolayout的布局原理、流程，就知道我说的了。问题先关了。

**Comment by MorningStarJ** [comment]
> @MorningStarJ 建议你去研究下Controller、Autolayout的布局原理、流程，就知道我说的了。问题先关了。
你没看到我写的CRTagView？我知道layoutsubview以后才能拿到正确的高度，问题就是在layoutsubview以后也拿不到正确的计算高度

**Comment by zekunyan** [comment]
@MorningStarJ 我运行你的Demo没有发现任何问题
<img width="396" alt="image" src="https://user-images.githubusercontent.com/5687881/56778344-60870800-6808-11e9-9fc6-ed6a2ccdf186.png">

你写的CRTagView也没有在ViewController里面使用，我没有义务帮你查代码Bug。

还有你在`viewDidLoad`里面使用`tagView.preferredMaxLayoutWidth = tagView.bounds.width`就是会导致宽度错误，以致高度错误，我说的是事实。
