### ISSUE TITLE
TTGTagCollectionAlignmentFillByExpandingWidthExceptLastLine排版下只有一行的时候有问题

### ISSUE THREAD

**Issue by zh20102618** [zekunyan/TTGTagCollectionView#79]
需求：当只有一行并且第一行填充不满的时候，希望能靠左展示。
因为不确定是不是多行，所以采用TTGTagCollectionAlignmentFillByExpandingWidthExceptLastLine排版，但是只有一行的时候会自动把每个item按照TTGTagCollectionAlignmentFillByExpandingWidth进行排版，我去查看了源码，发现TTGTagCollectionAlignmentFillByExpandingWidthExceptLastLine确实只考虑多行的情况，希望能修复，谢谢！

**Comment by zekunyan** [comment]
@zh20102618 有Demo或者示例么？

**Comment by zh20102618** [comment]
我上传了图片你看下
![Simulator Screen Shot - iPhone 5s - 2019-05-13 at 17 45 05](https://user-images.githubusercontent.com/10481822/57612310-3030bf00-75a7-11e9-864f-6bc3ba9c6756.png)

**Comment by zh20102618** [comment]
部分二级分类只有1个item，但是会自动填充满，如果只有一行的话，那么第一行应该就是最后一行，应该靠排版才对

**Comment by zh20102618** [comment]
按照你的逻辑来说，确实没问题，但是在实际应用的中的话，类似于这样的情况肯定是希望只有一行的时候不要填充满才是比较合理的吧。因为你的判断是只判断是不是最后一行，而忽略了是不是第一行的情况。

**Comment by zekunyan** [comment]
@zh20102618 这是个好问题=。=，可以先试试自己加个类型，提个MR？
