### ISSUE TITLE
TTGTextTagCollectionView Select delegates are not getting called in swift

### ISSUE THREAD

**Issue by umairgillani94** [zekunyan/TTGTagCollectionView#80]
contentSize delegate method is getting called but the selection delegate methods are not calling in swift

**Comment by zekunyan** [comment]
Demo code ?

**Comment by umairgillani94** [comment]
class MYVC : UIViewController {

        tagsView.delegate = self
        tagsView.numberOfLines = 2
        tagsView.alignment = .fillByExpandingWidth
        tagsView.enableTagSelection = true

        tagsView.addTag("First")
        tagsView.addTag("Second")
        tagsView.addTag("Third")
}




extension MYVC : TTGTextTagCollectionViewDelegate {
    func textTagCollectionView(_ textTagCollectionView: TTGTextTagCollectionView!, updateContentSize contentSize: CGSize) {
        
    }
    
    func textTagCollectionView(_ textTagCollectionView: TTGTextTagCollectionView!, didTapTag tagText: String!, at index: UInt, selected: Bool, tagConfig config: TTGTextTagConfig!) {
        print("selected text : ",tagText)
    }
    
    func textTagCollectionView(_ textTagCollectionView: TTGTextTagCollectionView!, canTapTag tagText: String!, at index: UInt, currentSelected: Bool, tagConfig config: TTGTextTagConfig!) -> Bool {
        print("selected text : ",tagText)
        return true
    }
}

**Comment by zekunyan** [comment]
@umairgillani94 I try the code below and i works for me. So i don't know why your code didn't work...

```swift
import UIKit
import TTGTagCollectionView

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let tagsView = TTGTextTagCollectionView(frame: CGRect.init(x: 16, y: 100, width: 200, height: 200))
        self.view.addSubview(tagsView)
        
        tagsView.delegate = self
        tagsView.numberOfLines = 2
        tagsView.alignment = .fillByExpandingWidth
        tagsView.enableTagSelection = true
        
        tagsView.addTag("First")
        tagsView.addTag("Second")
        tagsView.addTag("Third")
    }
    
}

extension ViewController: TTGTextTagCollectionViewDelegate {
    func textTagCollectionView(_ textTagCollectionView: TTGTextTagCollectionView!, updateContentSize contentSize: CGSize) {
        print("Update size: \(contentSize)")
    }
    
    func textTagCollectionView(_ textTagCollectionView: TTGTextTagCollectionView!, didTapTag tagText: String!, at index: UInt, selected: Bool, tagConfig config: TTGTextTagConfig!) {
        print("didTap")
    }
    
    func textTagCollectionView(_ textTagCollectionView: TTGTextTagCollectionView!, canTapTag tagText: String!, at index: UInt, currentSelected: Bool, tagConfig config: TTGTextTagConfig!) -> Bool {
        print("canTap");
        return true;
    }
}
```

**Comment by umairgillani94** [comment]
I used IBOutlet is there any issue in that?

**Comment by zekunyan** [comment]
@umairgillani94 May be... I will try this later.

**Comment by umairgillani94** [comment]
oka i will try your above code.

**Comment by umairgillani94** [comment]
only the update size delegate function is called by above implementation. Other 2 show following warnings and are not called 

Instance method 'textTagCollectionView(_:didTapTag:at:selected:tagConfig:)' nearly matches optional requirement 'textTagCollectionView(_:didTapTag:at:selected:tagConfig:)' of protocol 'TTGTextTagCollectionViewDelegate'
Make 'textTagCollectionView(_:didTapTag:at:selected:tagConfig:)' private to silence this warning


Instance method 'textTagCollectionView(_:canTapTag:at:currentSelected:tagConfig:)' nearly matches optional requirement 'textTagCollectionView(_:canTapTag:at:currentSelected:tagConfig:)' of protocol 'TTGTextTagCollectionViewDelegate'
Make 'textTagCollectionView(_:canTapTag:at:currentSelected:tagConfig:)' private to silence this warning

Can you please help me out?

**Comment by BaluNaik** [comment]
@umairgillani94 @zekunyan guys, it works with `IBOutlet `.

**Comment by umairgillani94** [comment]
@BaluNaik it's not working for me can you please share your code.

**Comment by greatcodeeer** [comment]
Try this:
```
func textTagCollectionView(_ textTagCollectionView: TTGTextTagCollectionView!, didTap tag: TTGTextTag!, at index: UInt) {
print("didTap@\(tag.tagId)")
}``
```

**Comment by trsa74** [comment]
@greatcodeeer I tried your code but still it is not working. Means there is no function callback when we select/deselect tags. Can you put your entire code here. Thanks.

**Comment by trsa74** [comment]
Oh sorry, I forgot to attach delegate to my tagView
// tagView.delegate = self
