### ISSUE TITLE
TTGTagCollectionView height and scroll

### ISSUE THREAD

**Issue by karek314** [zekunyan/TTGTagCollectionView#83]
Hello,
Thanks for very decent library.

I noticed that TTGTagCollectionView limits height of view and enables scrolling if there are many tags inside. I'm using TTGTagCollectionView inside UITableViewCell, so I don't need TTGTagCollectionView to additionally enable scrolling. How do I prevent this?

Best Regards
K.

**Comment by zekunyan** [comment]
@karek314 Use `preferredMaxLayoutWidth` to get correct height for your cell.

**Comment by karek314** [comment]
How does Width would fix height? Bit confused.

**Comment by zekunyan** [comment]
@karek314 The Demo code has the example.

**Comment by karek314** [comment]
I checked all of them and I could't allow indefinite height of TTGTagCollectionView. I was able to disable scroll view, however in that case TTGTagCollectionView just cuts remaining tags, they are outside of view.

Can you give example configuration how to make height of TTGTagCollectionView unlimited without scroll view?

Thank you.

**Comment by zekunyan** [comment]
@karek314 
```
@interface TTGExample4TableViewCell ()
@end

@implementation TTGExample4TableViewCell

- (void)awakeFromNib {
    [super awakeFromNib];
    
    // Alignment
    _tagView.alignment = TTGTagCollectionAlignmentFillByExpandingWidth;
    
    // Use manual calculate height
    _tagView.manualCalculateHeight = YES;
}

- (void)setTags:(NSArray<NSString *> *)tags {
    [_tagView removeAllTags];

    NSMutableArray *textTags = [NSMutableArray new];
    for (NSString *string in tags) {
        TTGTextTag *textTag = [TTGTextTag tagWithContent:[TTGTextTagStringContent contentWithText:string] style:[TTGTextTagStyle new]];
        [textTags addObject:textTag];
    }
    [_tagView addTags:textTags];

    // Use manual height, update preferredMaxLayoutWidth
    _tagView.preferredMaxLayoutWidth = [UIScreen mainScreen].bounds.size.width - 16;
    
    // Random selected
    for (NSInteger i = 0; i < 3; i++) {
        [_tagView updateTagAtIndex:arc4random_uniform((uint32_t)tags.count) selected:YES];
    }    
}

@end
```

**Comment by karek314** [comment]
With mentioned settings:
```
 _tagView.alignment = TTGTagCollectionAlignmentFillByExpandingWidth;
_tagView.preferredMaxLayoutWidth = [UIScreen mainScreen].bounds.size.width - 16;
_tagView.manualCalculateHeight = YES;
```

It still does not work. Height of TTGTagCollectionView is smaller than content and scroll view inside it is activated.

**Comment by zekunyan** [comment]
@karek314 Show me your demo code.

**Comment by brahmostech** [comment]
same problem can't scroll when content bigger then TTGTagCollectionView.

**Comment by karek314** [comment]
@zekunyan Thanks! It's solved now. While preparing demo for you, I figured out that it's crucial to set `tagView.preferredMaxLayoutWidth = UIScreen.main.bounds.size.width - 16;` at the very beginning of **setTags** function in **UITableViewCell** class.

**Comment by zekunyan** [comment]
@karek314 Yes~，`tagView.preferredMaxLayoutWidth` is the same as `UILabel.preferredMaxLayoutWidth`
