### ISSUE TITLE
How to increase taglistview height in vertical  scrolldirection on the basis of tags inside it 

### ISSUE THREAD

**Issue by EndLess728** [zekunyan/TTGTagCollectionView#86]
I don't want that scrollview for vertical , i want to increase its height dynamically on the basibs of contents inside it instead of specific height and scrollview

**Comment by zekunyan** [comment]
Please check the demo.

**Comment by swapneshp-spaceo** [comment]
Hi, i am looking for same, but not getting any perfect output, could you please share some details, how we will get this condition, Height according to content size.
