### ISSUE TITLE
如何实现动态高度？

### ISSUE THREAD

**Issue by 1129798217** [zekunyan/TTGTagCollectionView#87]
如何实现动态高度？标签要越界了，就自动增加collectionview高度

**Comment by zekunyan** [comment]
Demo有的

**Comment by 1129798217** [comment]
> Demo有的

嗯，看到了，CGSize size = [tagCollectionView intrinsicContentSize]; 
插件写的不错啊，挺好用的。

**Comment by zekunyan** [comment]
> > Demo有的
> 
> 嗯，看到了，CGSize size = [tagCollectionView intrinsicContentSize];
> 插件写的不错啊，挺好用的。

新版即将到来~
