### ISSUE TITLE
ScrollView contentSize inaccurate

### ISSUE THREAD

**Issue by maxwell44** [zekunyan/TTGTagCollectionView#91]
设置好数据源后 
调用 reload 方法
contentSize 不准确。视图显示后  contentSize正确了

尝试在 reload 后 调用 [self layoutIfNeeded] 也没有成功

使用了AutoLayout来布局。

**Comment by zekunyan** [comment]
设置下preferredMaxLayoutWidth

**Comment by maxwell44** [comment]
这个是设置过的 上面遗漏了说明 在
 - (void)layoutSubviews {
  [super layoutSubviews];
  self.tagCollectionView.preferredMaxLayoutWidth
}

**Comment by zekunyan** [comment]
在init的时候就设置

**Comment by maxwell44** [comment]
此问题已解决
