### ISSUE TITLE
使用masonry约束TTGTextTagCollectionView导致contentSize异常

### ISSUE THREAD

**Issue by leezhihua** [zekunyan/TTGTagCollectionView#94]
`[self.contentView addSubview:tagview];
[tagview mas_makeConstraints:^(MASConstraintMaker *make) {
    make.top.left.bottom.right.equalTo(@0);
}];`

使用masonry，cell第一次显示的时候高度比实际的要高很多，滑动后第二次出现就正常了

**Comment by zekunyan** [comment]
使用preferredMaxLayoutWidth
