### ISSUE TITLE
UITableView嵌套TTGTagCollectionView高度怎么计算

### ISSUE THREAD

**Issue by deepindo** [zekunyan/TTGTagCollectionView#96]
看完了demo以及closed的issue，想请问一下，我是纯代码编写；
tableViewCell中放tags，TTGTextTagCollectionView是用懒加载的

- (TTGTextTagCollectionView *)tagsView {
    if (!_tagsView) {
        _tagsView = [[TTGTextTagCollectionView alloc]init];
        // Use manual calculate height
        _tagsView.manualCalculateHeight = YES;
        _tagsView.preferredMaxLayoutWidth = kScreenWidth - 40;
        
        // Alignment
        _tagsView.alignment = TTGTagCollectionAlignmentFillByExpandingWidth;
        
        
        TTGTextTagConfig *config = _tagsView.defaultConfig;
        config.textFont = kSysFont(14);
        config.textColor = Color_Text_Gray;
        config.selectedTextColor = [UIColor colorWithRed:0.18 green:0.19 blue:0.22 alpha:1.00];
        config.backgroundColor = [UIColor colorWithRed:0.98 green:0.91 blue:0.43 alpha:1.00];
        config.selectedBackgroundColor = [UIColor colorWithRed:0.97 green:0.64 blue:0.27 alpha:1.00];
        
        _tagsView.horizontalSpacing = 6.0;
        _tagsView.verticalSpacing = 8.0;
        
        config.borderColor = [UIColor colorWithRed:0.18 green:0.19 blue:0.22 alpha:1.00];
        config.selectedBorderColor = [UIColor colorWithRed:0.18 green:0.19 blue:0.22 alpha:1.00];
        config.borderWidth = 1;
        config.selectedBorderWidth = 1;
        
        config.shadowColor = [UIColor blackColor];
        config.shadowOffset = CGSizeMake(0, 0.3);
        config.shadowOpacity = 0.3f;
        config.shadowRadius = 0.5f;
        
        config.cornerRadius = 7;
        
        config.enableGradientBackground = YES;
        config.gradientBackgroundStartColor = [UIColor orangeColor];
        config.selectedGradientBackgroundStartColor = [UIColor yellowColor];
        config.gradientBackgroundEndColor = [UIColor yellowColor];
        config.selectedGradientBackgroundEndColor = [UIColor grayColor];
        config.gradientBackgroundStartPoint =CGPointMake(0, 0);
        config.gradientBackgroundEndPoint = CGPointMake(1, 1);
    }
    return _tagsView;
}

cell的init方法如下布局

[self.tagsView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.faultDescLabel.mas_bottom).offset(10);
        make.left.equalTo(self.bgView).offset(10);
        make.right.equalTo(self.bgView).offset(-10);
        make.height.equalTo(@(kScreenHeight));
    }];

cell的模型中如下设置的
- (void)setModel:(IssueList *)model {
   
    [self.tagsView removeAllTags];
    [self.tagsView addTags:model.faultTypes];

    self.tagsView.alignment = TTGTagCollectionAlignmentFillByExpandingWidth;
    //self.tagsView.preferredMaxLayoutWidth = kScreenWidth - 40;
    [self.tagsView reload];
    [self updateConstr];
}

cell更新布局如下：
- (void)updateConstr {
    [self.tagsView mas_updateConstraints:^(MASConstraintMaker *make) {
        make.height.equalTo(@(self.tagsView.contentSize.height));
    }];
}

现在对于UITableView中的heightForRow应该如何拿到动态高度呢，我看demo中用的estimatedRowHeight，没有实现heightForRow的代理方法，也可以显示，不知道怎么弄的？

盼回复！

**Comment by zekunyan** [comment]
目前用preferredMaxLayoutWidth最稳妥

**Comment by zekunyan** [comment]
estimatedRowHeight方式不保证效果，不再做支持。

**Comment by deepindo** [comment]
你根据都没有去看我问的问题，estimatedRowHeight并非我想用，而是参照你demo来写的；对于preferredMaxLayoutWidth来实现效果，我用了，但是并没有效果，若是并不支持纯代码的方式，我无话可说，但是麻烦看一下再close.

**Comment by zekunyan** [comment]
根据你放出来的Code，无法判断是否有问题、问题在哪里，我不负责接入场景排除Bug，如果要找问题，请上传完整可复现问题的Project
